- khard/carddav_object.py
Thank you for this interesting project. I recently started using it and noticed the following issue.
The BDAY field can either be in the format BDAY:19950415 or BDAY:1995-04-15 (see http://www.imc.org/pdi/vcard-21.txt in Section Birthdate).
khard currently only supports the format without hyphens. This is a problem since e.g. Thunderbird and Android create contacts in the extended format with hyphens (however, they can read both formats) and as a result their birthday field is ignored by khard.
This merge request allows khard to read both formats.
> Allow BDAY to be in the extended format of ISO 8601

- .travis.yml
- khard/khard.py
- setup.py
- test/__init__.py
- test/test_command_line_interface.py
If the infrastructure is in place we can start to add tests for different things.
The first things that come to mind (and that might already be somewhat complicatet) are
- parsing config files
- parsing example vcard files
- exporting and reimporting contacts
If we write tests that interact with the vcard store and the config file we have to take care to _never_ use the config file and vcards of the user.
Fixes #62.
> Add a test suite and a first test

- khard/actions.py
- khard/khard.py
- misc/zsh/_khard
I found this old commit lying around. It might fit #139, @DamienCassou?
The command will print the full file names of all matching contacts.  The file
names are the original vcard files in the address book on disk, not temporary
files.  The command can be used for scripting, when khard should be used
together with some other tool.
> Add new command "filename"

- khard/address_book.py
- khard/config.py
- khard/helpers.py
- khard/khard.py
- test/test_address_book.py
- test/test_helpers.py
This PR moves as much responsibility about managing collections of vcards to the address book (as I believe it is not really the responsibility of the config class to manage vcards).
Also the AddressBook class is split up so it can be extended more easily.  Currently an abstract base class, one class to load from a directory of vcard files and one class to collect many such folders into one abstract address book are implemented.  The AddressBookCollection class takes over many of the responsibilities of the config class about managing vcards from different address books.  One idea to extend this could be that we could use a cache to reduce the time needed for parsing all the vcards as it looks like this is the main bottle neck for khard's performance at the moment.  But that is a …
> More object oriented address book

- khard/address_book.py
- khard/config.py
- khard/khard.py
- test/fixture/foo.abook/minimal3.vcf
- test/test_address_book.py
- test/test_command_line_interface.py
Nearly all of the operations that where performed on the old contacts list can easily be performed on the dict as well.  The only exception is the storing of several contacts with the same UID (but such a thing arguably shouldn't happen anyways).
This results in a drastic cleanup of the code.  But I think there is more to gain here.  But I was not able to figure out how and where the shortened uids are used.  So this part is postponed until I clean up the corresponding code from the other side (khard.py and config.py).
The last commit (66fa5d1) brings some actual speed improvement in some situations (e.g. `khard ls -f lucas`).
> Turn contact list in AddressBook into a dict

- khard/address_book.py
- khard/config.py
- khard/khard.py
This PR is still a bit WIP.
I am trying to use the AddressBookCollection more.  At the same time I try to sort out the different paths that can and need to .load() an AddressBook.
The "Simplify derived search regex" commit (8b98889) gives me a bit of a speed improvement.
For measurements I use [this zsh function](https://github.com/lucc/shell-config/blob/master/functions/comp) to compare the execution time of 10 runs of a command:
```
$ comp './khard-runner.py ls -f' './khard-runner.py ls -f -a other' './khard-runner.py ls -f simon' './khard-runner.py ls -f -a other simon'
1  17.33s user 0.34s system 99% cpu 17.666 total
2  6.14s user 0.27s system 100% cpu 6.394 total
3  2.48s user 0.23s system 100% cpu 2.699 total
4  1.84s user 0.16s system 100% cpu 1.994 total
```
whereas on develop I …
> Use AddressBookCollection and regex speedup

- README.md
The old site is gone. This PR replaces the link with Baïkal's GitHub.  
Alternatively the [main site](http://sabre.io/baikal) could be used.
> Fix Baïkal link

- khard/carddav_object.py
- test/test_carddav_object.py
- test/test_yaml.py
Also enable adding/editing these.
Recreated #202 because the merge onto develop wasn't possible without (someone else's) manual intervention.
I still need to add tests.
> Display ABLABELs for URLs and Private Objects

- khard/actions.py
- khard/khard.py
- misc/zsh/_khard
- test/test_command_line_interface.py
This is the corresponding PR for #179.  Until now the unification of show-export and edit-source is done. The unification of the different ls versions is underway.
I am happy about any feedback.
> Redesign command line interface

- khard/carddav_object.py
- khard/helpers.py
- test/test_vcard_wrapper.py
- test/test_yaml.py
Also allow for ABLABELs in `_add_organisation`.
Fixes #221, #225.
Still needs handling for ADR (maybe others?) and unit tests. Feedback welcome, but I might not get back to this until next week, so here's a start.
~~In its current form, this also breaks sorting in` _get_multi_property`, which causes several tests to fail.~~
> Use dict internally for fields with ABLABEL

- khard/helpers.py
- test/test_helpers.py
- test/test_yaml.py
As @lucc discovered in while testing #226, a string containing ": " will be output into a yaml as a normal string, but will then fail to parse because it looks like a yaml mapping value.
This patch works around that problem by forcing any string containing ": " to be output into yaml as a multiline string, where such sequences are ignored. I've also included a test for the round trip, which should hopefully work even if the implementation of the fix changes.
> Force strings that look like yaml mapping values to be displayed as multiline strings

- AUTHORS
- README.rst
- doc/source/conf.py
@scheibler I do not know if the AUTHORS file served any kind of purpos or if
any tool needs it.  If it is just for humans I would rather put this info
into the readme which is now not our main documentation document any longer.
I left you as the author in the docs.  I hope that is ok with you.
> Move mentioning of the authors to README

- khard/config.py
- test/test_config.py
Whilst working on the [Reproducible Builds](https://reproducible-builds.org/) effort we noticed that *khard* could not be built reproducibly.
This is because it includes the absolute build directory in the documentation via the `SPEC_FILE` attribute. This commit calculates this value dynamically instead.
(This was originally filed in Debian as [#943471](https://bugs.debian.org/943471).)
> Make the build reproducible

- README.md
- doc/source/index.rst
- doc/source/man/khard.rst
The current wording may, falsely, imply that `khard` runs is Linux-only, which isn't the case.
> Works fine on macOS and the *BSDs

- khard/cli.py
- khard/helpers.py
- khard/khard.py
- test/test_command_line_interface.py
https://github.com/scheibler/khard/issues/179#issuecomment-576060333
Things you can do with this
* `python3 -m khard ls -F name,birthday` (like `khard bdays`, but it doesn't sort, doesn't exclude missing birthdays, and outputs in a different format)
* `python3 -m khard ls -pF emails.home.0,name` (shows first home email address for each user)
* `python3 -m  khard ls --fields phone_numbers.cell.0,phone_numbers` (shows first cell number, and all phone numbers in python format)
* `python3 -m khard ls -p -F Name,post_addresses.home.0.region,post_addresses.home.0.code` (name, state and zip code)
The list of properties can be seen with
`grep '@property' -A1 khard/carddav_object.py`
(Additional fields can easily be added by making them attributes in carddav_object.py)
For backwards compatibility …
> Command line interface: Implement --fields for list command

- .gitignore
- khard/address_book.py
- khard/cli.py
- khard/khard.py
- test/test_cli.py
- test/test_khard.py
Fixes: https://github.com/scheibler/khard/issues/257
This adds new arguments to the `add-email` sub command, `-H`, `--header` and `--all`, which allow extracting the email addresses from the given header, or all of the headers if requested.
This also adds a loop over the found email addresses so that the user is given the opportunity to add each to a contact.
A later extension of this might allow `-H` and `--header` to accept a list of headers to use, but this isn't implemented here.
> Feature: add-email custom headers

- khard/khard.py
When adding contacts through the add-email functionality it can give the
name of the contact and then ask to create it. It would be easier to add
the contacts if we at least guess the name parts.
> Offer the first and last names to the user to use

- doc/source/man/khard.conf.rst
- khard/address_book.py
- khard/khard.py
- test/test_address_book.py
- test/test_command_line_interface.py
Expand environment variables for the `addressbooks.<name>.path` config
values.  With this, you can set an addressbook path to
`$XDG_DATA_HOME/contacts/foo`, for example.
This may be backwards incompatible for users that use literal dollar
characters (`$`) in their paths.  If the environment variable expansion
is possible, it will be unintentionally expanded.  If it is not
possible, however, it will not be expanded.  So the compatibility issue
is only when the path is expandable (e.g.
`~/classes/english/$LANG/contacts`).  With this change, I do not know of
a way to express these kinds of paths (escaping doesn't work).  Yet, I
doubt anyone would come across this issue, let alone have a literal
dollar sign in their path.
> Expand env vars for addressbooks path config

- .travis.yml
The nightly python version seems to be on 3.10 already:
https://travis-ci.org/github/scheibler/khard/jobs/721931462#L184
Triggered by #277.
> Run tests also on python 3.9

- khard/carddav_object.py
While having a quick look at #279 I noticed that this block tests `self.version` but prints `version`.
> Fix minor error in VCardWrapper.__init__() warning

- khard/config.py
After updating khard/khal stopped working for me. Adjusting the import fixed this issue for me.
> Quickfix for no method error (validate)

- khard/carddav_object.py
When formatting the postal address, empty fields cause empty lines and sometimes weird appearance.
For example:
````
Address
HOME: 
Main street 20
1234 AB Blaricum
, Netherlands
````
This PR removes empty fields from the address structure so they do not cause misbehaviour.
After the patch:
````
Address
HOME: 
Main street 20
1234 AB Blaricum
Netherlands
````
> Reduce empty address lines in "details" output

- README.md
- doc/source/conf.py
- doc/source/index.rst
- doc/source/man/khard.rst
- setup.py
Just to avoid some frustration for folks that found khard when looking
for a CardDAV client.
Note: CardDAV is also used throughout the code, but I don't think that
that's how people find khard. The important parts are the README and the
docs, and the description in `setup.py`.
Fixes: #303
> docs: clarify that khard does not speak CardDAV

- khard/carddav_object.py
- khard/helpers/__init__.py
- test/test_yaml_editable.py
replace the YAMLEditable.to_yaml() method with ruamel serialization.
migrate some yaml formatting to the helpers module.
> Use ruamel.yaml for YAMLEditable

- khard/carddav_object.py
- khard/helpers/__init__.py
- khard/helpers/typing.py
- test/test_helpers.py
- test/test_yaml_editable.py
> Fix yaml conversion of post addresses

- README.md
Fixed the wrong URL and pointed it to the correct one.
> fixing wrong URL for vCard format interoperability

- khard/contacts.py
- khard/khard.py
- test/test_query.py
- test/test_vcard_wrapper.py
This is a step for #272. The `N` attributes are not yet handled correctly.
> Nullable properties

- doc/source/examples/khard.conf.example
- doc/source/man.rst
- doc/source/man/khard.conf.rst
- khard/config.py
- khard/data/config.spec
- test/fixture/discover.conf
- test/test_config.py
As mentioned in #203 I took a shot at allowing globbing. The way this works is pretty similar to khal, essentially if you set the type option of an addressbook to `discover`, the path is run through `glob.glob` with `recursive = True`, and a separate addressbook is added for every folder that is found.
The first commit fixes a small typo, if preferred, I can also open a separate PR for that.
> Add discover addressbook type
